use_frameworks!

platform :ios, '10.0'

target 'WSFloatingButtonControlSwift_Example' do
  pod 'WSFloatingButtonControlSwift', :path => '../'

  target 'WSFloatingButtonControlSwift_Tests' do
    inherit! :search_paths

    
  end
end
